console.log("Primeira linha \nSegunda linha")
console.log("O meu nome é 'João'")
console.log('O meu nome é "João"')
console.log("O meu nome é \"João\"")
console.log(`A multiplicação de 5 por 3 é ${5 * 3}`)
console.log("O " + "meu " + "nome " + "é " + "João.")    